### ISSUE TITLE
[QUESTION] Why do we need image processing in intranet?

### ISSUE THREAD

**Issue by ribeirojose** [neo-empresarial/intranet#10]
https://github.com/neo-empresarial/intranet/blob/87ad3f2c34da477add6d7a3cbbffd097509b8728/Pipfile#L21

**Comment by lukasab** [comment]
I think this is needed to process profile pictures but I'm not sure. I got this from NIR branch

**Comment by ribeirojose** [comment]
Got it. A quick search in the repo doesn't show any reference to Piilow or PIL. I'll open a PR deleting it.
