### ISSUE TITLE
Django app documentation

### ISSUE THREAD

**Issue by ribeirojose** [neo-empresarial/intranet#12]
Hey guys! I was trying to run the project locally but I couldn't quite get the grasp of how I should run the django app. Would you please point me to where I can find more about that?

**Comment by lukasab** [comment]
Just run: `python manage.py runserver`

https://docs.djangoproject.com/en/2.2/intro/tutorial01/

Don't forget to migrate and build the frontend first.

I forgot to add the backend documentation part in the README.

**Comment by lukasab** [comment]
After you manage to run it can you close this issue?
